### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by aljica** [Kungbib/swedish-bert-models#2]
Running the code

```
from transformers import pipeline

nlp = pipeline('ner', model='KB/bert-base-swedish-cased-ner', tokenizer='KB/bert-base-swedish-cased-ner')

nlp('Kalle och Pelle startar firman Kalle och Pelle.')
```
yields the following error:
```
Model name 'KB/bert-base-swedish-cased-ner' was not found in model name list (bert-base-uncased, ....) 
We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/KB/bert-base-swedish-cased-ner/modelcard.json' 
was a path or url to a model card file named modelcard.json 
or a directory containing such a file but couldn't find any such file at this path or url.                                                                                                      
Creating an empty model card.
```
transformers 2.5.1 and pytorch 1.4.0 is used.

**Comment by marma** [comment]
I wonder if you were unlucky enough to time your download precisely to when we updated the model. Could you try again?

**Comment by aljica** [comment]
Hi, I tried again but to no avail.

This is the full output I get when I run the code: https://pastebin.com/ujmyDmm9

I did something a bit different from your instructions though. I went to pytorch.org, scrolled down a little bit and chose the settings: [Stable, Windows, Pip, Python, None] and installed torch that way. Running 
```
pip install -r requirements.txt
```
yielded the following error: https://pastebin.com/NV9m4Sus

But I don't think that's the problem.

Running the code without "-ner" at the end of model and tokenizer, like so:
```
model='KB/bert-base-swedish-cased', tokenizer='KB/bert-base-swedish-cased'
```
downloads 5 (?) different files and then exits (one of which is 499MB, i assume that's the .bin file with the model). Then when I run the code again, the same problem "Creating empty model card" occurs.

**Comment by aljica** [comment]
The error message generated by the line 
```
nlp = pipeline('ner', model='KB/bert-base-swedish-cased-ner', tokenizer='KB/bert-base-swedish-cased-ner')
```
 never actually prevented the code from progressing further, which means typing
```
x = nlp('Kalle och Pelle startar firman Kalle och Pelle.')
print(x)
```
works perfectly well. Rookie mistake. This has been resolved!
