### ISSUE TITLE
Use IOB format for tagging instead of entitiy tags

### ISSUE THREAD

**Issue by EmilStenstrom** [Kungbib/swedish-bert-models#4]
These BERT models are fantastic! Thanks for releasing them to the wild like this.

I've played around with `KB/bert-base-swedish-cased-ner` to see if it's possible to build a full NER pipeline using it. I've quickly ran into problems when working with multi-word entities. The problem is that there is not enough information in the returned reply to know it two adjacent tokens should be merged or not:

"New York is a great city" returns the same thing as "New is a great place, so is York": 

```python
[
    {'word': 'New', 'score': 0.9996529221534729, 'entity': 'LOC'}, 
    {'word': 'York', 'score': 0.9996837377548218, 'entity': 'LOC'}
]
```

There are many ways to solve this, and one way would be to switch to [IOB](https://en.wikipedia.org/wiki/Inside%E2%80%93outside%E2%80%93beginning_(tagging)) (either version). This changes the tagging scheme slightly to look like this:

"New York is a great city":

```python
[
    {'word': 'New', 'score': 0.9996529221534729, 'entity': 'B-LOC'}, 
    {'word': 'York', 'score': 0.9996837377548218, 'entity': 'I-LOC'}
]
```

"New is a great place, so is York": 

```python
[
    {'word': 'New', 'score': 0.9996529221534729, 'entity': 'B-LOC'}, 
    {'word': 'York', 'score': 0.9996837377548218, 'entity': 'B-LOC'}
]
```

This makes sure there is enough information in the reply to recreate multi word tokens.

If you want to convert SUC 3.0 to IOB format for training (I'm not sure how you are doing your training), you can use this script: https://github.com/EmilStenstrom/suc_to_iob

**Comment by marma** [comment]
Thanks!

There is an IOB-version, but we've haven't had time to evaluate it yet. There is a potential problem in that the model might not to 100% learn to tag correctly. For example for long sequences the first token might get dropped if the score is too low, but the remaining ones might not resulting in broken IOB sequences.

That said, I'll upload an IOB-version later today if you want to try it out.

And a tip: if you pass `ignore_labels=[]` to `pipeline(...)` the `O` labels will make it clear when a new entity begins.

**Comment by EmilStenstrom** [comment]
Ah, that sounds like a serious issue. A broken tagging scheme is worse than none at all I guess...

Thanks for the ignore_labels trick, I figured it out too yesterday while reading the transformers code.

An alternative would be if there was info in the result from transformers that aligned the tokens with the original text. I’ve posted an issue (https://github.com/huggingface/transformers/issues/3284) in the transformers repo to ask for that.

That would also solve another problem: reconstructing the spacing between multi-word tokens. Today, I would have to write some heuristic to determine how to merge tokens together. But that’s a transformers issue, not a Bert one :)

Thanks again!

**Comment by marma** [comment]
ping @EmilStenstrom https://huggingface.co/KB/bert-base-swedish-cased-neriob

**Comment by EmilStenstrom** [comment]
@marma Nice! Will test right away.

**Update:** Works great in my simple (few manual sentences) tests. The confidence score seems to be slightly higher too.

**Comment by marma** [comment]
@EmilStenstrom It might be because the underlying model ha been trained for slightly longer, or just a fluke :)

I'm closing the issue if that is ok by you.
